export const CHANGE_DEPARTURE = "CHANGE_DEPARTURE";
export const CHANGE_ARRIVAL = "CHANGE_ARRIVAL";
export const LOAD_PLACES = "LOAD_PLACES";
export const LOAD_PLACES_ERROR = "LOAD_PLACES_ERROR";
export const LOAD_PLACES_SUCCESS = "LOAD_PLACES_SUCCESS";
